INPUT:
  TRAIN: '/DISLOCATIONS/'
  TEST: '/DISLOCATIONS/'

TRAINING:
    TRAINING_SET: 'dislocations'
    EXPERIMENT_NAME: 'baseline'
    MODEL_DIR: 'models'
    MODEL: 'init'
    CUDA: True
    GPU_ID: 0
    SEED: 42
    INPUT_LAYER: 1
    IMAGE_SIZE_H: 512
    IMAGE_SIZE_W: 512
    LOAD_PRE_TRAINING: False
    LEAARNING_RATE: 0.001
    START_EPOCH: 0
    END_EPOCHS: 200
    NMS_EPOCH0: 10
    NMS_OTHERS: 10
    BATCH_SIZE: 5
    PLOT_EVERY_X_BATCHES: 20
    OPTIMIZER: Adam
    BASE_LR: 0.001
    SAVE_MODEL_STEP: 1
    NUM_WORKERS: 8

TEST:
    IMAGE_SIZE_H: 256
    IMAGE_SIZE_W: 256
    TESTING: True
    TESTING_EVERY: 1
    NMS: 10
    BATCH_SIZE: 5
    MIN_PROB: 0.5
    WEIGHTS: ''

VISUALIZER:
    ENABLE:1

LOGGING:

  ENABLE_LOGGING: True
  ENABLE_PLOTTING: False
  ENABLE_VISUALIZING: True
  FID: 1000

  LOG_INTERVAL: 100
  PLOT_INTERVALS: 10
  IMG_DIR: 'images/'
  LOG_DIR: 'logs/'